package com.dune

import com.lagradost.cloudstream3.plugins.CloudstreamPlugin
import com.lagradost.cloudstream3.plugins.BasePlugin
import com.lagradost.cloudstream3.extractors.*

@CloudstreamPlugin
class IndiaSocialBookPlugin: BasePlugin() {
    override fun load() {
        // Register Main API Provider
        registerMainAPI(IndiaSocialBook())

        // Register All Extractors (Streamwish, Vidhide, Doodstream, Filemoon, Voe, Streamtape variants, etc.)
        registerExtractorAPI(Streamwish())
        registerExtractorAPI(Streamhihi())
        registerExtractorAPI(Javsw())
        registerExtractorAPI(VidHidePro())
        registerExtractorAPI(VidhideVIP())
        registerExtractorAPI(Javlion())
        registerExtractorAPI(VidHidePro1())
        registerExtractorAPI(VidHidePro2())
        registerExtractorAPI(VidHidePro3())
        registerExtractorAPI(VidHidePro4())
        registerExtractorAPI(VidHidePro6())
        registerExtractorAPI(VidHidePro7())
        registerExtractorAPI(Dhcplay())
        registerExtractorAPI(Smoothpre())
        registerExtractorAPI(Dhtpre())
        registerExtractorAPI(Peytonepre())
        registerExtractorAPI(Movearnpre())
        registerExtractorAPI(Dintezuvio())
        registerExtractorAPI(HgLink())
        registerExtractorAPI(RyderJet())
        registerExtractorAPI(MyCloudZ())
        registerExtractorAPI(Turboplayers())
        registerExtractorAPI(Javclan())
        registerExtractorAPI(Javggvideo())
        registerExtractorAPI(swhoi())
        registerExtractorAPI(MixDropis())
        registerExtractorAPI(Javmoon())
        registerExtractorAPI(StbP2P())
        registerExtractorAPI(Playerupnone())
        registerExtractorAPI(Turtleviplay())
        registerExtractorAPI(Turboviplay())
        registerExtractorAPI(MixDropAG())
        registerExtractorAPI(MixDropMy())
        registerExtractorAPI(Vidguardto())
        registerExtractorAPI(LULUSTREAM())
        registerExtractorAPI(LULUVDO())
        registerExtractorAPI(LULUVDOO())
        registerExtractorAPI(LULUPVP())
        registerExtractorAPI(LULUDLC())
        registerExtractorAPI(LULU0())
        registerExtractorAPI(LULUX08())
        registerExtractorAPI(VidNest())
        registerExtractorAPI(FileMoon2())
        registerExtractorAPI(FileMoonIn())
        registerExtractorAPI(FileMoonSx())
        registerExtractorAPI(Bysedikamoum())
        registerExtractorAPI(Bysezoexe())
        registerExtractorAPI(Filemoonx08())
        registerExtractorAPI(Player4Me())
        registerExtractorAPI(Vip4me())
        registerExtractorAPI(RPMShare())
        registerExtractorAPI(UpnsOnline())
        registerExtractorAPI(EmbedSeek())
        registerExtractorAPI(VipSeekPlayer())
        registerExtractorAPI(EasyVidPlayer())
        registerExtractorAPI(VipEasyVidPlayer())
        registerExtractorAPI(DoodStream())
        registerExtractorAPI(Playmogo())
        registerExtractorAPI(DoodDoply())
        registerExtractorAPI(DoodPmExtractor())
        registerExtractorAPI(DoodVideo())
        registerExtractorAPI(Ds2Play())
        registerExtractorAPI(d000d())
        registerExtractorAPI(Dooood())
        registerExtractorAPI(StreamTAPE())
        registerExtractorAPI(Watchadsontape())
        registerExtractorAPI(Stape())
        registerExtractorAPI(StreamTapeNet())
        registerExtractorAPI(StreamTapeXyz())
        registerExtractorAPI(ShaveTape())
        registerExtractorAPI(Lancewhoisdifficult())
        registerExtractorAPI(Javlesbians())
        registerExtractorAPI(Stevenfamilyedge())
    }
}